### ISSUE TITLE
Alignment Process Stalling: No MAF Files Generated After 15 Days

### ISSUE THREAD

**Issue by luca-Wang** [RiversDong/GageTracker#3]
Thank you for developing this convenient software. We successfully ran a test with a small dataset. However, during the full-scale analysis, the LAST software has been running for 15 days without completing, and not a single MAF file has been fully generated. The reference genome is 3 GB, while the genomes of 15 species range from 1 to 4 GB, and 1 species have genomes of 30 GB. I expected at least the smaller genomes to have completed alignment by now.

Do you have any suggestions to address this issue? Many thanks!

**Comment by RiversDong** [comment]
We haven’t yet tested GageTracker on a genome as large as 30 Gb. However, we offer a parameter, -lg, specifically designed to support genome alignment on large genomes. You can find details on using this parameter in Section 3.2 of the manual. This parameter in GageTracker may achieve accurate alignment for genomes of this size.

Additionally, we recommend using the -mos parameter to mask outgroup species, which can help reduce the overall runtime of the genome alignment process.

Therefore, please include at least two parameters in your command line: -mos and -lg.

Please feel free to contact us if you encounter any other issues; we’d appreciate your feedback.

Best wishes,

**Comment by luca-Wang** [comment]
Thanks for your response. We observed significant speed differences across various versions of lastal in other projects, so we used different versions of lastal to run the analyses.

I ran two sets of parameters:
(1) Parameter1: -ao -mos -lg -p 10, lastal version 1254, ran for 42 days;
(2) Parameter2: -ao -mos -p 10, lastal version 1592, ran for 16 days.
I would expect at least a 1Gb alignment to a 3Gb MAF file to be generated, as we previously completed a lastal alignment independently in just one day.

Could it be that the parameters set by GageTracker for lastal are too stringent? Or perhaps, could I run lastal independently to generate the MAF file first, and then proceed with GageTracker?

**Comment by RiversDong** [comment]
The parameters used by GageTracker are stringent. By default, GageTracker employs the -m50 parameter when calling LAST, which could achieve performance comparable to lastz. However, this accuracy is gained at the cost of slower genome alignment speeds. In contrast, the default parameter for lastal is -m10, which significantly accelerates alignment by default when using lastal.

As you mentioned, theoretically, you can run lastal independently to generate the MAF file and then proceed with GageTracker. Please refer to the -rbh (-step2) parameter in the manual. However, note that to follow this approach, you’ll need to pre-prepare the input files generated by -step1 (this step can be replaced by independently running lastal).

As shown by your test results, different versions of the lastal software vary in alignment speed. To accelerate computation, you may consider installing a faster version of lastal or improving efficiency by adjusting the alignment parameters. This parameter can be found in lines 231 and 241 of the alignM.py file. We offer the following recommendations for setting this parameter:
▪	Using the -m50 parameter achieves accuracy comparable to lastz (this accuracy is gained at the cost of slower genome alignment speeds);
▪	For evolutionary closed species, we recommend -m10 to avoid generating excessively large MAF files;
▪	For distantly related species with divergence times over 200 Mya, -m50 is recommended to ensure accuracy;
▪	If prioritizing ultra-fast genome alignment, the default lastal alignment parameters can be used.

In the GageTracker folder path, run the following script to modify the lastal parameter.
sed -i 's/lastal -P 6 -C2 -u0 -m50/lastal -P 6 -C2 -u0 -m25/'  alignM.py

**Comment by RiversDong** [comment]
Do you have any additional questions regarding this? If not, I will consider this issue resolved and close it.

**Comment by luca-Wang** [comment]
Thank you very much. I followed one of your advice and independently generated the MAF file for GageTracker, then proceeded with the analysis starting from step 2. I used the -m100 parameter (high sensitivity) for the lastal alignment, and I have obtained some preliminary results. You can go ahead and close this issue.
